<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> Team Up!</title>
	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="stylesheet.css">
</head>

<body>

<nav class="navbar navbar-inverse"> 
	<div class="container-fluid"> 
		<div class="navbar-header"> 
			<button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false"> 
				<span class="sr-only">Toggle navigation</span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
			</button> 
			<a href="#" class="navbar-brand">Team up!</a> 
		</div> 
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9"> 
			<ul class="nav navbar-nav"> 
				<li class="active"><a href="login.php">Iniciá sesión</a></li> 
				<li><a href="register.php">Registrate</a></li> 
				<li><a href="faq.php">FAQ's</a></li>
			</ul> 

			<ul class="nav navbar-nav navbar-right">
        		<? if (is_logged_in()): ?>
	        		<li class="dropdown">
	          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?= @$_SESSION['user']['nombre'] ?> <span class="caret"></span></a>
	          			
	          			<ul class="dropdown-menu">
				            <li><a href="#">Action</a></li>
				            <li><a href="#">Another action</a></li>
				            <li><a href="#">Something else here</a></li>
				            <li role="separator" class="divider"></li>
				            <li><a class="logout" href="#">Cerrar sesión</a></li>
				        </ul>
				    </li>
			    <? endif ?>
			</ul>

		</div> 
	</div> 
</nav>

