<div class="background background-home"></div>
<div class="container">
	<div class="row">
		<div class="col-sm-offset-5 col-sm-6">
			<form class="form-horizontal" method="post">

			  	<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
						<div class="logo">
							<img src="images/logo_TeamUp-sm.png">
						</div>
						<div class="home-text">
							La red social que te permite armar tu equipo, reservar canchas cerca de tu casa o simplemente hablar de lo que te apasiona: el fútbol!
						</div>
						
						
						<?php if (isset($errors)): ?>
							<?php foreach($errors as $fieldName => $message): ?>
							<div class="alert alert-danger" role="alert"><?= $message ?></div>
							<?php endforeach ?>
						<?php endif ?>

					</div>	
				</div>

				<div class="form-group <?= isset($errors) ? get_error_css_class($errors['email']) : '' ?>" >
			    	<label for="inputEmail3" class="col-sm-4 control-label"></label>
			    	<div class="col-sm-8">
				   		<input type="email" class="form-control" id="inputEmail3" placeholder="E-mail" name="email" value="<?= @$_POST['email'] ?>">
			    	</div>
				</div>



			  <div class="form-group <?= isset($errors) ? get_error_css_class(@$errors['password']) : '' ?>" >
			    <label for="inputPassword3" class="col-sm-4 control-label"></label>
			    <div class="col-sm-8">
			      <input type="password" class="form-control" id="inputPassword3" name="password" value="<?= @$_POST['password']?>" placeholder="Contraseña">
			    </div>
			  </div>


			  <div class="form-group">
			    <div class="col-sm-offset-4 col-sm-8">
			      <div class="checkbox">
			        <label>
			          <input type="checkbox"> Recordarme
			        </label>
			      </div>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-7 col-sm-5">
			      <button type="submit" class="btn btn-success login-button">Iniciar sesión</button>
			    </div>
			  </div>

			</form>

		    <div class="row">
		      <label class="col-sm-offset-4 col-sm-8">
		        <a class="links" href="">Olvidé mi contraseña</a>
		      </label>
		    </div>
	    </div>
	</div>
</div>
