<div class="background background-home"></div>
<div class="container">
	<div class="row">
		<div class="col-sm-offset-3 col-sm-6">
			<form class="form-horizontal" method="post">

			  	<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
						<h1>Ingresá al sitio!</h1>
						
						<? if (isset($errors)): ?>
							<? foreach($errors as $fieldName => $message): ?>
							<div class="alert alert-danger" role="alert"><?= $message ?></div>
							<? endforeach ?>
						<? endif ?>

					</div>	
				</div>

				<div class="form-group <?= isset($errors) ? get_error_css_class($errors['email']) : '' ?>" >
			    	<label for="inputEmail3" class="col-sm-4 control-label"></label>
			    	<div class="col-sm-8">
			    		<div class="input-group">
	        				<span class="input-group-addon">@</span>
				    		<input type="email" class="form-control" id="inputEmail3" placeholder="E-mail" name="email" value="<?= @$_POST['email'] ?>">
			    		</div>
			    	</div>
				</div>



			  <div class="form-group <?= isset($errors) ? get_error_css_class(@$errors['password']) : '' ?>" >
			    <label for="inputPassword3" class="col-sm-4 control-label"></label>
			    <div class="col-sm-8">
			      <input type="password" class="form-control" id="inputPassword3" name="password" value="<?= @$_POST['password']?>" placeholder="Contraseña">
			    </div>
			  </div>


			  <div class="form-group">
			    <div class="col-sm-offset-4 col-sm-8">
			      <div class="checkbox">
			        <label>
			          <input type="checkbox"> Recordarme
			        </label>
			      </div>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-4 col-sm-8">
			      <button type="submit" class="btn btn-default">Iniciar sesión</button>
			    </div>
			  </div>

			</form>

		    <div class="row">
		      <label class="col-sm-offset-4 col-sm-8">
		        <hr/>
		        <a class="links" href="">Olvidé mi contraseña</a>
		      </label>
		    </div>
	    </div>
	</div>
</div>
