<div class="container">
	<div class="row">

		<div class="col-sm-offset-3 col-sm-6">
			
			<form class="form-horizontal" method="POST">

				<div class="form-group">
					<div class="col-sm-offset-4 col-sm-8">
						<h1>Registrate!</h1>
						
						<?php if (isset($errors)): ?>
							<div class="alert alert-danger" role="alert">
								<ul>
									<?php foreach($errors as $fieldName => $message): ?>
										<li><?= $message ?></li>
									<?php endforeach ?>
								</ul>
							</div>
						<?php endif ?>

					</div>	
				</div>

			  <div class="form-group <?= isset($errors) ? $formRegister->getErrorCssClass(@$errors['name']) : '' ?>">
			    <label for="name" class="col-sm-4 control-label">Nombre</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="name" placeholder="Nombre" value="<?= @$_POST['name'] ?>" name="name">
			    </div>
			  </div>
			  <div class="form-group <?= isset($errors) ? $formRegister->getErrorCssClass(@$errors['lastname']) : '' ?>">
			    <label for="lastname" class="col-sm-4 control-label">Apellido</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="lastname" placeholder="Apellido" value="<?= @$_POST['lastname'] ?>" name="lastname">
			    </div>
			  </div>


			  <div class="form-group">
			  	<label for="teamName" class="col-sm-4 control-label">Soy hincha de</label>
			  	<div class="col-sm-8">
				  	<select class="form-control" id="teamName" name="teamName">
				  		<option>-- Elegí tu club --</option>
				  		<?php foreach ($formRegister->getTeamNames() as $teamName): ?>
				  			<option <?= $teamName == @$_POST['teamName'] ? 'selected' : ''?> >
				  				<?= $teamName ?></option>
				  		<?php endforeach ?>
					
					</select>
				</div>
			  </div>

			  <div class="form-group <?= isset($errors) ? $formRegister->getErrorCssClass(@$errors['email']) : '' ?>">
			    <label for="email" class="col-sm-4 control-label">E-mail</label>
			    <div class="col-sm-8">
			    	<div class="input-group">
        				<span class="input-group-addon">@</span>
			    		<input type="email" class="form-control" id="email" name="email" value="<?= @$_POST['email'] ?>" placeholder="E-mail">
			    	</div>
			    </div>
			  </div>


			  <div class="form-group <?= isset($errors) ? $formRegister->getErrorCssClass(@$errors['profilePic']) : '' ?>">
			    <label for="imgProfile" class="col-sm-4 control-label">Foto de perfil</label>
			    <div class="col-sm-8">
			    	<div class="input-group">
			    		<input type="file" class="form-control" id="profilePic" name="profilePic" value="<?= @$_POST['profilePic'] ?>">
			    	</div>
			    </div>
			  </div>


			  <div class="form-group <?= isset($errors) ? $formRegister->getErrorCssClass(@$errors['password']) : '' ?>">
			    <label for="password" class="col-sm-4 control-label">Nueva contraseña</label>
			    <div class="col-sm-8">
			      <input type="password" class="form-control" id="password" value= "<?= @$_POST['password'] ?>" name="password" placeholder="Contraseña">
			    </div>
			  </div>

			  <div class="form-group <?= isset($errors) ? $formRegister->getErrorCssClass(@$errors['repeatPassword']) : '' ?>">
			    <label for="repeatPassword" class="col-sm-4 control-label">Repetir contraseña</label>
			    <div class="col-sm-8">
			      <input type="password" class="form-control" id="repeatPassword" value="<?= @$_POST['repeatPassword'] ?>" name="repeatPassword" placeholder="Repetir contraseña">
			    </div>
			  </div>

			  <div class="form-group">
			    <div class="col-sm-offset-4 col-sm-8">
			      <button type="submit" class="btn btn-default">Registrarme</button>
			    </div>
			  </div>
			</form>

		    
	    </div>
	</div>
</div>